### ISSUE TITLE
Crash on android 11

### ISSUE THREAD

**Issue by PhucDuy** [Unity-Technologies/gametune-example-game#2]
Hi Unity, 
I integrated Gametune for my game. 
Here's my sdk infromation.
Gametune Unity SDK 2.6.0
Unity 2018.4
TargetSdkVersion is 30
buildToolsVersion is 30.0.2

After release, I got a crash report in Android 11 which cause by gametune sdk. 
Please update to support Android 11.
`
Caused by java.lang.SecurityException: getDataNetworkTypeForSubscriber
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
       at android.os.Parcel.createException(Parcel.java:2357)
       at android.os.Parcel.readException(Parcel.java:2340)
       at android.os.Parcel.readException(Parcel.java:2282)
       at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
       at com.unity3d.gametune.connectivity.ConnectivityMonitor.connectionStatusChanged(ConnectivityMonitor.java:7)
      at com.unity3d.gametune.connectivity.ConnectivityNetworkCallback.onCapabilitiesChanged(ConnectivityNetworkCallback.java:1)
       at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3327)
       at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3607)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.os.HandlerThread.run(HandlerThread.java:67)
`

**Comment by richardtop** [comment]
Hi Phuc, could you please reach out to me at richard.topchii@unity3d.com and I'll help with resolving this issue. Please, attach any useful information (logs, crash reports, description of when the crash happens) to help us troubleshoot it.
Looking forward to your email.
Richard, from the Unity GameTune team.

**Comment by PhucDuy** [comment]
Hi @richardtop, I sent an email for you. I hope we can fix this issue soon.

**Comment by richardtop** [comment]
Hi Phuc, thanks. Our team is looking at your issue already!

**Comment by richardtop** [comment]
Hi, the issue has been confirmed and fixed in the latest versions of the SDK.
I suggest using GameTune SDK v2.7.1 or higher when targeting devices with Android API level 30.

Latest available GameTune SDKs are always available for download [at the documentation website](http://docs.gametune.unity3d.com/#downloads).
